### ISSUE TITLE
X.log -- Error setting up server dbus instance

### ISSUE THREAD

**Issue by thezoggy** [Celedhrim/docker-kodi-server#18]
do you also see dbus crashing in X.log after starting up pulseaudio? 

```
2020-02-03 20:22:53,136 dbus server error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/xpra/server/dbus/dbus_common.py", line 12, in dbus_exception_wrap
    v = fn()
  File "/usr/lib/python2.7/dist-packages/xpra/x11/server.py", line 1366, in make_dbus_server
    return X11_DBUS_Server(self, os.environ.get("DISPLAY", "").lstrip(":"))
  File "/usr/lib/python2.7/dist-packages/xpra/server/dbus/dbus_server.py", line 38, in __init__
    session_bus = init_session_bus()
  File "/usr/lib/python2.7/dist-packages/xpra/dbus/common.py", line 22, in init_session_bus
    _session_bus = dbus.SessionBus(private=private)
  File "/usr/lib/python2.7/dist-packages/dbus/_dbus.py", line 211, in __new__
    mainloop=mainloop)
  File "/usr/lib/python2.7/dist-packages/dbus/_dbus.py", line 100, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 122, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
2020-02-03 20:22:53,138 Error setting up server dbus instance:
2020-02-03 20:22:53,138   org.freedesktop.DBus.Error.Spawn.ExecFailed
2020-02-03 20:22:53,138   /usr/bin/dbus-launch terminated abnormally without any error message
```

**Comment by Celedhrim** [comment]
Yep I have the same , but n the head in works ( at least for me) so I've never dig this :)

**Comment by thezoggy** [comment]
just switched to matrix branch, latest X.log

```
X.Org X Server 1.19.6
Release Date: 2017-12-20
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.15.0-124-generic x86_64 Ubuntu
Current Operating System: Linux fbccf2c63948 4.19.107-Unraid #1 SMP Thu Mar 5 13:55:57 PST 2020 x86_64
Kernel command line: BOOT_IMAGE=/bzimage initrd=/bzroot pti=off spectre_v2=off l1tf=off mds=off nospec_store_bypass_disable no_stf_barrier
Build Date: 30 November 2020  08:01:56PM
xorg-server 2:1.19.6-1ubuntu4.8 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.34.0
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.:100.log", Time: Fri Feb 26 04:05:50 2021
(++) Using config file: "/etc/xpra/xorg.conf"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
2021-02-26 04:05:52,681 Warning: failed to create socket directory '/run/user/0/xpra'
2021-02-26 04:05:52,682  [Errno 2] No such file or directory: '/run/user/0/xpra'
2021-02-26 04:05:52,682 Warning: cannot create socket '/run/user/0/xpra/fbccf2c63948-100':
2021-02-26 04:05:52,682  [Errno 2] No such file or directory
2021-02-26 04:05:52,682  ($XDG_RUNTIME_DIR has not been created?)
2021-02-26 04:05:52,682 created unix domain socket: /root/.xpra/fbccf2c63948-100
2021-02-26 04:05:52,683 created unix domain socket: /run/xpra/fbccf2c63948-100
/bin/sh: 1: dbus-launch: not found
dbus-launch failed to start using command 'dbus-launch --close-stderr':

 exit code is 127

2021-02-26 04:05:52,781 Warning: menu forwarding is disabled:
2021-02-26 04:05:52,782  cannot load dbus helper: org.freedesktop.DBus.Error.Spawn.ExecFailed: /usr/bin/dbus-launch terminated abnormally without any error message
2021-02-26 04:05:52,836 Warning: enc_pillow failed its self test
2021-02-26 04:05:52,837  No module named numpy
2021-02-26 04:05:52,843 vpx: vp8 encoding failed: No module named numpy
2021-02-26 04:05:52,847 vpx: vp9 encoding failed: No module named numpy
2021-02-26 04:05:52,849 vpx: vp9 encoding failed: No module named numpy
2021-02-26 04:05:52,849 vpx: all the codecs have failed! (vp8, vp9, vp9)
2021-02-26 04:05:52,857 x264: h264 encoding failed: No module named numpy
2021-02-26 04:05:52,857 x264: all the codecs have failed! (h264)
2021-02-26 04:05:52,857 Warning: enc_x264 failed its self test
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
2021-02-26 04:05:52,871 x265: h265 encoding failed: No module named numpy
2021-02-26 04:05:52,871 x265: all the codecs have failed! (h265)
2021-02-26 04:05:52,871 Warning: enc_x265 failed its self test
2021-02-26 04:05:52,942 ffmpeg: h264+mp4 encoding failed: No module named numpy
2021-02-26 04:05:52,943 ffmpeg: vp8+webm encoding failed: No module named numpy
2021-02-26 04:05:52,945 ffmpeg: mpeg4+mp4 encoding failed: No module named numpy
2021-02-26 04:05:52,945 ffmpeg: all the codecs have failed! (h264+mp4, vp8+webm, mpeg4+mp4)
2021-02-26 04:05:52,947 Warning: csc_swscale failed its self test
2021-02-26 04:05:52,947  No module named numpy
2021-02-26 04:05:53,002 Warning: failed to load the mdns avahi publisher:
2021-02-26 04:05:53,002  No module named avahi
2021-02-26 04:05:53,002  either fix your installation or use the 'mdns=no' option
2021-02-26 04:05:53,827 Warning: webcam forwarding is disabled
2021-02-26 04:05:53,827  the virtual video directory '/sys/devices/virtual/video4linux' was not found
2021-02-26 04:05:53,827  make sure that the 'v4l2loopback' kernel module is installed and loaded
2021-02-26 04:05:53,827 found 0 virtual video devices for webcam forwarding
2021-02-26 04:05:53,841 pulseaudio server started with pid 146
W: [pulseaudio] main.c: This program is not intended to be run as root (unless --system is specified).
E: [pulseaudio] core-util.c: Failed to connect to system bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
E: [pulseaudio] core-util.c: Failed to connect to system bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
E: [pulseaudio] core-util.c: Failed to connect to system bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
E: [pulseaudio] core-util.c: Failed to connect to system bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
E: [pulseaudio] core-util.c: Failed to connect to system bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
E: [pulseaudio] core-util.c: Failed to connect to system bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
E: [pulseaudio] core-util.c: Failed to connect to system bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
E: [pulseaudio] core-util.c: Failed to connect to system bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
E: [pulseaudio] core-util.c: Failed to connect to system bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
E: [pulseaudio] core-util.c: Failed to connect to system bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
E: [pulseaudio] core-util.c: Failed to connect to system bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
W: [pulseaudio] authkey.c: Failed to open cookie file '/root/.config/pulse/cookie': No such file or directory
W: [pulseaudio] authkey.c: Failed to load authentication key '/root/.config/pulse/cookie': No such file or directory
W: [pulseaudio] authkey.c: Failed to open cookie file '/root/.pulse-cookie': No such file or directory
W: [pulseaudio] authkey.c: Failed to load authentication key '/root/.pulse-cookie': No such file or directory
W: [pulseaudio] server-lookup.c: Unable to contact D-Bus: org.freedesktop.DBus.Error.Spawn.ExecFailed: /usr/bin/dbus-launch terminated abnormally without any error message
W: [pulseaudio] main.c: Unable to contact D-Bus: org.freedesktop.DBus.Error.Spawn.ExecFailed: /usr/bin/dbus-launch terminated abnormally without any error message

Warning: running as root
Warning: failed to import GStreamer 1.x:
 Namespace Gst not available
2021-02-26 04:05:54,253 Error: failed to query sound subsystem:
2021-02-26 04:05:54,253  query did not return any data
2021-02-26 04:05:54,257 Warning: failed to load or register our dbus notifications forwarder:
2021-02-26 04:05:54,257  org.freedesktop.DBus.Error.Spawn.ExecFailed: /usr/bin/dbus-launch terminated abnormally without any error message
2021-02-26 04:05:54,257  if you do not have a dedicated dbus session for this xpra instance,
2021-02-26 04:05:54,258  use the 'notifications=no' option
2021-02-26 04:05:54,260 Warning: cannot load dbus helper:
2021-02-26 04:05:54,260  org.freedesktop.DBus.Error.Spawn.ExecFailed: /usr/bin/dbus-launch terminated abnormally without any error message
2021-02-26 04:05:54,265 dbus server error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/xpra/server/dbus/dbus_common.py", line 12, in dbus_exception_wrap
    v = fn()
  File "/usr/lib/python2.7/dist-packages/xpra/x11/server.py", line 1366, in make_dbus_server
    return X11_DBUS_Server(self, os.environ.get("DISPLAY", "").lstrip(":"))
  File "/usr/lib/python2.7/dist-packages/xpra/server/dbus/dbus_server.py", line 38, in __init__
    session_bus = init_session_bus()
  File "/usr/lib/python2.7/dist-packages/xpra/dbus/common.py", line 22, in init_session_bus
    _session_bus = dbus.SessionBus(private=private)
  File "/usr/lib/python2.7/dist-packages/dbus/_dbus.py", line 211, in __new__
    mainloop=mainloop)
  File "/usr/lib/python2.7/dist-packages/dbus/_dbus.py", line 100, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 122, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
DBusException: org.freedesktop.DBus.Error.Spawn.ExecFailed: /usr/bin/dbus-launch terminated abnormally without any error message
2021-02-26 04:05:54,266 Error setting up server dbus instance:
2021-02-26 04:05:54,266   org.freedesktop.DBus.Error.Spawn.ExecFailed
2021-02-26 04:05:54,266   /usr/bin/dbus-launch terminated abnormally without any error message
2021-02-26 04:05:54,289 started command '/usr/bin/kodi --standalone -p --nolirc' with pid 175
2021-02-26 04:05:54,289 xpra X11 version 2.1.3-r17247M 64-bit
2021-02-26 04:05:54,289  uid=0 (root), gid=0 (root)
2021-02-26 04:05:54,289  running with pid 6 on Linux Ubuntu 18.04 bionic
2021-02-26 04:05:54,290  connected to X11 display :100 with 24 bit colors
2021-02-26 04:05:54,344 xpra is ready.
2021-02-26 04:05:54,368 Warning: cannot load enc_vpx video encoder:
2021-02-26 04:05:54,368  no supported encodings!
2021-02-26 04:05:54,369 62.9GB of system memory
/usr/lib/x86_64-linux-gnu/kodi/kodi-xrandr: Failed to get size of gamma for output default
libEGL warning: DRI2: failed to authenticate
libva info: VA-API version 1.1.0
libva info: va_getDriverName() returns -1
libva error: va_getDriverName() failed with unknown libva error,driver_name=(null)
Failed to open VDPAU backend libvdpau_nvidia.so: cannot open shared object file: No such file or directory
sh: 1: nmblookup: not found
sh: 1: nmblookup: not found
sh: 1: nmblookup: not found
sh: 1: nmblookup: not found
sh: 1: nmblookup: not found
sh: 1: nmblookup: not found
sh: 1: nmblookup: not found
sh: 1: nmblookup: not found
sh: 1: nmblookup: not found
sh: 1: nmblookup: not found
sh: 1: nmblookup: not found
sh: 1: nmblookup: not found
sh: 1: nmblookup: not found
sh: 1: nmblookup: not found
sh: 1: nmblookup: not found
sh: 1: nmblookup: not found
sh: 1: nmblookup: not found
sh: 1: nmblookup: not found
sh: 1: nmblookup: not found
sh: 1: nmblookup: not found
sh: 1: nmblookup: not found
sh: 1: nmblookup: not found
sh: 1: nmblookup: not found
sh: 1: nmblookup: not found
sh: 1: nmblookup: not found
sh: 1: nmblookup: not found
sh: 1: nmblookup: not found
sh: 1: nmblookup: not found
sh: 1: nmblookup: not found
sh: 1: nmblookup: not found
sh: 1: nmblookup: not found
sh: 1: nmblookup: not found
sh: 1: nmblookup: not found
sh: 1: nmblookup: not found
sh: 1: nmblookup: not found
sh: 1: nmblookup: not found
sh: 1: nmblookup: not found
sh: 1: nmblookup: not found
sh: 1: nmblookup: not found
sh: 1: nmblookup: not found
sh: 1: nmblookup: not found
sh: 1: nmblookup: not found
sh: 1: nmblookup: not found
sh: 1: nmblookup: not found
sh: 1: nmblookup: not found
sh: 1: nmblookup: not found
sh: 1: nmblookup: not found
sh: 1: nmblookup: not found
sh: 1: nmblookup: not found
sh: 1: nmblookup: not found
sh: 1: nmblookup: not found
sh: 1: nmblookup: not found
sh: 1: nmblookup: not found
sh: 1: nmblookup: not found
sh: 1: nmblookup: not found
sh: 1: nmblookup: not found
sh: 1: nmblookup: not found
sh: 1: nmblookup: not found
sh: 1: nmblookup: not found
/usr/lib/x86_64-linux-gnu/kodi/kodi-xrandr: Failed to get size of gamma for output default
```

**Comment by thezoggy** [comment]
per the log
```
2021-02-26 04:05:54,257 Warning: failed to load or register our dbus notifications forwarder:
2021-02-26 04:05:54,257  org.freedesktop.DBus.Error.Spawn.ExecFailed: /usr/bin/dbus-launch terminated abnormally without any error message
2021-02-26 04:05:54,257  if you do not have a dedicated dbus session for this xpra instance,
2021-02-26 04:05:54,258  use the 'notifications=no' option
```

sounds like we just update the xpra startup argument in kodi-run-wrapper.sh with  `--notifications=no`  to stop the dbus spam since you run dbus systemwide

per xpra manual:
```
--notifications=yes|no

Enable or disable forwarding of system notifications. System notifications require the xpra server to have its own instance of a dbus daemon, if it is missing a warning will be printed on startup. This switch disables the feature entirely, and avoids the warning.
```
